---
- name: debian | installing squid
  apt:
    name: "{{ squid_package }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Create cache directory
  file:
    path: "{{ item.path }}"
    mode: 0700
    owner: "proxy"
    group: "proxy"
    state: directory
  loop: "{{ squid_cache_dir }}"