---
# tasks file for ansible-squid

- import_tasks: set_facts.yml

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: config_squid.yml

- import_tasks: config_squid_transparent_proxy.yml
  when:
    - squid_transparent_proxy
    - squid_transparent_proxy_ferm
